<?php

use App\Actions\Inquiries\CreateInquiry;
use App\Actions\Inquiries\GenerateInquiryNumber;
use App\Models\Inquiry;
use App\Models\InquiryAttachment;
use App\Models\InquiryCategory;
use App\Models\User;
use Illuminate\Support\Carbon;

test('inquiry numbers are generated by prefix period and sequence', function () {
    $generator = app(GenerateInquiryNumber::class);
    $submittedAt = Carbon::parse('2026-07-10 19:13:00');

    $first = $generator->handle($submittedAt, 'kazm');
    $second = $generator->handle($submittedAt, 'KAZM');
    $nextMonth = $generator->handle(Carbon::parse('2026-08-01 00:00:00'), 'KAZM');

    expect($first['number'])->toBe('KAZM-0726-0001')
        ->and($first['prefix'])->toBe('KAZM')
        ->and($first['period'])->toBe('0726')
        ->and($first['sequence'])->toBe(1)
        ->and($second['number'])->toBe('KAZM-0726-0002')
        ->and($second['sequence'])->toBe(2)
        ->and($nextMonth['number'])->toBe('KAZM-0826-0001')
        ->and($nextMonth['sequence'])->toBe(1);
});

test('inquiries keep category review period snapshot', function () {
    $category = InquiryCategory::factory()->create([
        'review_days' => 90,
    ]);
    $creator = User::factory()->create();
    $submittedAt = Carbon::parse('2026-07-10 19:13:00');

    $inquiry = app(CreateInquiry::class)->handle([
        'category' => $category,
        'creator' => $creator,
        'title' => 'Неисправен кондиционер',
        'description' => 'Описание обращения',
        'submitted_at' => $submittedAt,
        'number_prefix' => 'KAZM',
    ]);

    expect($inquiry)
        ->toBeInstanceOf(Inquiry::class)
        ->number->toBe('KAZM-0726-0001')
        ->type->toBe(Inquiry::TYPE_PORTAL)
        ->status->toBe(Inquiry::STATUS_NEW)
        ->created_by_id->toBe($creator->id)
        ->inquiry_category_id->toBe($category->id)
        ->review_days->toBe(90)
        ->and($inquiry->review_due_date->toDateString())->toBe('2026-10-08');

    $category->update(['review_days' => 15]);

    expect($inquiry->fresh()->review_days)->toBe(90);
});

test('anonymous inquiries do not store creator', function () {
    $category = InquiryCategory::factory()->create();
    $creator = User::factory()->create();

    $inquiry = app(CreateInquiry::class)->handle([
        'category' => $category,
        'creator' => $creator,
        'anonymous' => true,
        'title' => 'Анонимное обращение',
    ]);

    expect($inquiry->type)->toBe(Inquiry::TYPE_ANONYMOUS)
        ->and($inquiry->created_by_id)->toBeNull();
});

test('inquiries can have file attachments with storage metadata', function () {
    $inquiry = Inquiry::factory()->create();
    $uploader = User::factory()->create();

    $attachment = InquiryAttachment::factory()
        ->for($inquiry)
        ->for($uploader, 'uploader')
        ->create([
            'original_name' => 'evidence.pdf',
            'stored_name' => 'evidence-stored.pdf',
            'mime_type' => 'application/pdf',
            'extension' => 'pdf',
            'file_type' => InquiryAttachment::TYPE_PDF,
            'size_bytes' => 120_500,
            'metadata' => ['pages' => 3],
        ]);

    expect($attachment->uuid)->not->toBeEmpty()
        ->and($attachment->inquiry->is($inquiry))->toBeTrue()
        ->and($attachment->uploader->is($uploader))->toBeTrue()
        ->and($attachment->metadata)->toBe(['pages' => 3])
        ->and($inquiry->attachments()->count())->toBe(1);
});
