<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <title>{{ __('Inquiry certificate') }} № {{ $inquiry->number }}</title>
        <style>
            * { font-family: 'DejaVu Sans', sans-serif; }
            body { color: #1f2937; font-size: 12px; line-height: 1.6; margin: 0 36px; }
            .header { border-bottom: 2px solid #1d4ed8; padding-bottom: 14px; margin-bottom: 20px; }
            .header h1 { font-size: 18px; color: #1d4ed8; margin: 0 0 4px 0; }
            .header .subtitle { color: #6b7280; font-size: 11px; }
            h2 { font-size: 13px; color: #1d4ed8; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin: 18px 0 6px 0; }
            .meta { width: 100%; border-collapse: collapse; margin-bottom: 8px; font-size: 11px; }
            .meta td { padding: 4px 8px 4px 0; vertical-align: top; }
            .meta td.label { color: #6b7280; width: 30%; white-space: nowrap; }
            .section { margin-bottom: 10px; }
            .section h3 { font-size: 12px; color: #111827; margin: 12px 0 4px 0; text-transform: uppercase; letter-spacing: 0.4px; }
            .section p { margin: 0; white-space: pre-line; }
            .footer { border-top: 1px solid #e5e7eb; margin-top: 24px; padding-top: 10px; font-size: 10px; color: #6b7280; }
            .footer .ai { font-style: italic; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>{{ __('Inquiry certificate') }} № {{ $inquiry->number }}</h1>
            <div class="subtitle">{{ __('Generated by AI assistant') }}</div>
        </div>

        <h2>{{ __('Inquiry details') }}</h2>
        <table class="meta">
            <tr>
                <td class="label">{{ __('Inquiry number') }}</td>
                <td>{{ $inquiry->number }}</td>
            </tr>
            <tr>
                <td class="label">{{ __('Subject') }}</td>
                <td>{{ $inquiry->title }}</td>
            </tr>
            <tr>
                <td class="label">{{ __('Category') }}</td>
                <td>{{ $inquiry->category?->fallback_name }}</td>
            </tr>
            <tr>
                <td class="label">{{ __('Status') }}</td>
                <td>{{ $inquiry->status }}</td>
            </tr>
            <tr>
                <td class="label">{{ __('Inquiry type') }}</td>
                <td>{{ $inquiry->type }}</td>
            </tr>
            <tr>
                <td class="label">{{ __('Inquiry date') }}</td>
                <td>{{ $inquiry->submitted_at->format('d.m.Y H:i') }}</td>
            </tr>
            <tr>
                <td class="label">{{ __('Review deadline') }}</td>
                <td>{{ $inquiry->review_due_date->format('d.m.Y') }}</td>
            </tr>
            <tr>
                <td class="label">{{ __('Applicant full name') }}</td>
                <td>{{ $inquiry->type === \App\Models\Inquiry::TYPE_ANONYMOUS ? __('Anonymous') : ($inquiry->applicant?->name ?? $inquiry->creator?->name ?? __('Not specified')) }}</td>
            </tr>
            @if ($inquiry->type !== \App\Models\Inquiry::TYPE_ANONYMOUS)
                <tr>
                    <td class="label">{{ __('Email') }}</td>
                    <td>{{ $inquiry->applicant?->email ?? $inquiry->creator?->email ?? __('Not specified') }}</td>
                </tr>
                <tr>
                    <td class="label">{{ __('Phone') }}</td>
                    <td>{{ $inquiry->applicant?->phone ?? __('Not specified') }}</td>
                </tr>
            @endif
            <tr>
                <td class="label">{{ __('Executor') }}</td>
                <td>{{ $inquiry->assignee?->name ?? __('Not assigned') }}</td>
            </tr>
            <tr>
                <td class="label">{{ __('Description') }}</td>
                <td>{{ $inquiry->description ?? __('No description provided') }}</td>
            </tr>
            <tr>
                <td class="label">{{ __('Response status') }}</td>
                <td>{{ $inquiry->response?->status ?? __('Not prepared') }}</td>
            </tr>
            <tr>
                <td class="label">{{ __('Inquiry outcome') }}</td>
                <td>{{ $inquiry->response?->outcome?->fallback_name ?? __('Not specified') }}</td>
            </tr>
        </table>

        <h2>{{ __('AI analysis') }}</h2>

        @foreach ([
            'summary' => __('Summary'),
            'facts' => __('Facts'),
            'category' => __('Category'),
            'processing' => __('Processing history'),
            'responses' => __('Responses and result'),
            'materials' => __('Materials and comments'),
            'risk' => __('Risk assessment'),
            'recommendations' => __('Recommendations'),
            'conclusion' => __('Conclusion'),
        ] as $key => $title)
            <div class="section">
                <h3>{{ $title }}</h3>
                <p>{{ $data[$key] ?? '' }}</p>
            </div>
        @endforeach

        <div class="footer">
            <div>{{ __('Inquiry certificate') }} № {{ $inquiry->number }} — {{ $generatedAt->format('d.m.Y H:i') }}</div>
            <div class="ai">{{ __('This report was generated automatically by the AI assistant and may contain errors.') }}</div>
        </div>
    </body>
</html>
